# Setup
title:               Paul Mcilwaine
tagline:             ''
description:         ''
url:                 https://pmcilwaine.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Paul Mcilwaine
  url:               https://www.linkedin.com/in/paulmcilwaine/
  email:             paul.mcilwaine@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:             1.1.0
google_analytics_id: UA-144481572-1
